import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import { initBuiltInEnvelopes, cleanupSelfScheduledTransfers, migrateTransferAmounts } from './data/envelopes.js'
import { ensureBuiltInCategories } from './data/categories.js'
import { cleanupPlanningAfterSelfTransferRemoval } from './data/planning.js'

// Ensure built-in data exists on first run
initBuiltInEnvelopes()
ensureBuiltInCategories()

// One-time migration for SPEC-009 fix: remove invalid self-transfers that were
// generated by the old "apply planned income" code path, and clean up any
// planning links that pointed at them.
const removedTransferIds = cleanupSelfScheduledTransfers()
cleanupPlanningAfterSelfTransferRemoval(removedTransferIds)

// Phase 43c: repair any envelope-transfer / scheduled-transfer amounts that were
// previously stored as strings (corrupted balance sums — NaN / wrong totals).
migrateTransferAmounts()

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
